SELECT
	br.id,
	br.REACTOR_NAME,
	br.MVAR_CAPACITY,
	as2.SUBSTATION_NAME
FROM
	REPORTING_WEB_UI_UAT.BUS_REACTOR br
LEFT JOIN REPORTING_WEB_UI_UAT.ASSOCIATE_SUBSTATION as2 ON
	as2.ID = br.FK_SUBSTATION