SELECT
	fb.ID,
	asb.SUBSTATION_NAME AS substation,
	vol.TRANS_ELEMENT_TYPE AS voltage,
	fb.MVAR,
	fb.IS_SWITCHABLE,
	fb.FILTERBANK_NUMBER
FROM
	REPORTING_WEB_UI_UAT.FILTER_BANK fb
LEFT JOIN REPORTING_WEB_UI_UAT.ASSOCIATE_SUBSTATION asb ON
	asb.id = fb.SUBSTATION_ID
LEFT JOIN REPORTING_WEB_UI_UAT.TRANS_ELEMENT_TYPE_MASTER vol ON
	vol.TRANS_ELEMENT_TYPE_ID = fb.VOLTAGE_ID