SELECT
	hlc.id,
	hlc.LINE_CIRCUIT_NAME,
	hlc.CIRCUIT_NO,
	line.voltage
FROM
	REPORTING_WEB_UI_UAT.HVDC_LINE_CIRCUIT hlc
LEFT JOIN (
	SELECT
		hlm.*, vol.TRANS_ELEMENT_TYPE AS voltage
	FROM
		REPORTING_WEB_UI_UAT.HVDC_LINE_MASTER hlm
	LEFT JOIN REPORTING_WEB_UI_UAT.TRANS_ELEMENT_TYPE_MASTER vol ON
		vol.TRANS_ELEMENT_TYPE_ID = hlm.FROM_VOLTAGE) line ON
	line.ID = HLC.HVDC_LINE_ID