SELECT
	hp.id,
	hp.POLE_NAME,
	stn.SUBSTATION_NAME,
	stn.voltage
FROM
	REPORTING_WEB_UI_UAT.HVDC_POLE hp
LEFT JOIN (
	SELECT
		as2.*, vol.TRANS_ELEMENT_TYPE AS voltage
	FROM
		REPORTING_WEB_UI_UAT.ASSOCIATE_SUBSTATION as2
	LEFT JOIN REPORTING_WEB_UI_UAT.TRANS_ELEMENT_TYPE_MASTER vol ON
		vol.TRANS_ELEMENT_TYPE_ID = as2.VOLTAGE_LEVEL) stn ON
	stn.id = hp.FK_SUBSTATION