SELECT
	lr.id,
	lr.REACTOR_NAME,
	lr.MVAR_CAPACITY,
	as2.SUBSTATION_NAME,
	ATLC.LINE_CIRCUIT_NAME
FROM
	REPORTING_WEB_UI_UAT.LINE_REACTOR lr
LEFT JOIN REPORTING_WEB_UI_UAT.ASSOCIATE_SUBSTATION as2 ON
	as2.ID = lr.FK_SUBSTATION
LEFT JOIN REPORTING_WEB_UI_UAT.AC_TRANSMISSION_LINE_CIRCUIT atlc ON
	ATLC.id = lr.FK_LINE_ID