SELECT
	ckt.id,
	ckt.LINE_CIRCUIT_NAME,
	ckt.CIRCUIT_NUMBER,
	ckt.LENGTH,
	line.voltage
FROM
	REPORTING_WEB_UI_UAT.AC_TRANSMISSION_LINE_CIRCUIT ckt
LEFT JOIN (
	SELECT
		lm.*, vol.TRANS_ELEMENT_TYPE AS voltage
	FROM
		REPORTING_WEB_UI_UAT.AC_TRANS_LINE_MASTER lm
	LEFT JOIN REPORTING_WEB_UI_UAT.TRANS_ELEMENT_TYPE_MASTER vol ON
		vol.TRANS_ELEMENT_TYPE_ID = lm.VOLTAGE_LEVEL ) line ON
	line.id = ckt.line_id