-- table creation
CREATE TABLE CODE_BOOK.APPLICATION_STATE (
    id NUMBER(38,0) NOT NULL UNIQUE,
	deleted_outage_processed_ts TIMESTAMP NOT NULL,
    CHECK (id IN (1))
);
-- initialization
INSERT INTO CODE_BOOK.APPLICATION_STATE (id, DELETED_OUTAGE_PROCESSED_TS) VALUES (1, TO_DATE('1970-01-01', 'YYYY-MM-DD'));

/*
-- setting the application state
UPDATE CODE_BOOK.APPLICATION_STATE SET DELETED_OUTAGE_PROCESSED_TS = CURRENT_TIMESTAMP WHERE id = 1;
*/