SELECT
	b.id,
	b.BUS_NAME,
	b.BUS_NUMBER,
	vol.TRANS_ELEMENT_TYPE AS voltage,
	as2.SUBSTATION_NAME
FROM
	REPORTING_WEB_UI_UAT.BUS b
LEFT JOIN REPORTING_WEB_UI_UAT.ASSOCIATE_SUBSTATION as2 ON
	as2.ID = b.FK_SUBSTATION_ID
LEFT JOIN REPORTING_WEB_UI_UAT.TRANS_ELEMENT_TYPE_MASTER vol ON
	vol.TRANS_ELEMENT_TYPE_ID = b.VOLTAGE
