SELECT *
FROM REPORTING_WEB_UI_UAT.ENTITY_MASTER x
WHERE x.IS_OUTAGE_ENTITY IN (1)

/*
 id|ENTITY_NAME|Table_name
 28|Filter Bank|FILTER_BANK
 16|BUS|BUS
 4|BUS REACTOR|BUS_REACTOR
 5|LINE_REACTOR|LINE_REACTOR
 8|GENERATING_UNIT|GENERATING_UNIT
 9|TRANSFORMER|TRANSFORMER
 10|FSC|FSC
 11|SVC|SVC
 12|TCSC|TCSC
 13|HVDC POLE|HVDC_POLE
 14|AC_TRANSMISSION_LINE_CIRCUIT|AC_TRANSMISSION_LINE_CIRCUIT
 15|HVDC_LINE_CIRCUIT|HVDC_LINE_CIRCUIT
 24|Bay|BAY
 /*